let batchPlan = null;
function resetBatchResults(){ $('tempoDisp').textContent='—';$('kgProd').textContent='—';$('batchComp').textContent='0';$('ultimoBatch').textContent='—';batchPlan=null; }
function prossimoInizioLavorativo(data){const d=new Date(data),g=d.getDay();if(g===0||(g===6&&d.getHours()>=6)){d.setDate(d.getDate()+(g===6?2:1));d.setHours(6,0,0,0)}else if(g===1&&d.getHours()<6)d.setHours(6,0,0,0);return d}
function fineFinestraLavorativa(data){const d=new Date(data);d.setDate(d.getDate()+(6-d.getDay()+7)%7);d.setHours(6,0,0,0);return d}
function minutiLavorativiDisponibili(inizio,limite){let corrente=prossimoInizioLavorativo(inizio),minuti=0;while(corrente<limite){const stop=fineFinestraLavorativa(corrente),fine=stop<limite?stop:limite;minuti+=Math.max(0,Math.floor((fine-corrente)/60000));if(fine>=limite)break;corrente=prossimoInizioLavorativo(fine)}return minuti}
function dataOraBatch(dataId,oraId){const data=$(dataId).value,ora=$(oraId).value;return data&&ora?new Date(data+'T'+ora+':00'):null}
function formattaTempo(minuti){return Math.floor(minuti/60)+' h '+minuti%60+' min'}
function calcBatch(){const portata=v('portataBatch'),kgPerBatch=v('kb'),inizio=dataOraBatch('dataPartenzaBatch','oraBatch'),limite=dataOraBatch('dataFine','oraFine');if(!(portata>0&&kgPerBatch>0&&inizio&&limite&&!isNaN(inizio)&&!isNaN(limite)&&limite>inizio)){resetBatchResults();return}const minuti=minutiLavorativiDisponibili(inizio,limite),kgProducibili=portata*minuti/60,batchCompleti=Math.floor(kgProducibili/kgPerBatch),residuo=kgProducibili-batchCompleti*kgPerBatch,ultimoParziale=residuo>0.000001?residuo:0;$('tempoDisp').textContent=formattaTempo(minuti);$('kgProd').textContent=fmt(kgProducibili)+' kg';$('batchComp').textContent=String(batchCompleti);$('ultimoBatch').textContent=ultimoParziale?fmt(ultimoParziale)+' kg (parziale)':'—';batchPlan={inizio,limite,portata,kgPerBatch,minuti,kgProducibili,batchCompleti,ultimoParziale}}
function fineBatch(kg){return fineLavorativa(batchPlan.inizio,Math.round(kg/batchPlan.portata*60))}
function formatoDataOra(data){return data.toLocaleDateString('it-IT')+' · '+data.toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}
function openBatchDetails(){calcBatch();if(!batchPlan)return alert('Inserisci data e ora di partenza e limite, portata e kg per batch validi.');const righe=[];for(let i=1;i<=batchPlan.batchCompleti;i++){const cumulativi=i*batchPlan.kgPerBatch;righe.push('<div class="histItem"><b>Batch '+i+'</b><p>'+fmt(batchPlan.kgPerBatch)+' kg</p><small>Completamento: '+formatoDataOra(fineBatch(cumulativi))+'</small></div>')}if(batchPlan.ultimoParziale)righe.push('<div class="histItem batchPartial"><b>Ultimo batch parziale</b><p>'+fmt(batchPlan.ultimoParziale)+' kg</p><small>Completamento: '+formatoDataOra(fineBatch(batchPlan.kgProducibili))+'</small></div>');$('batchDetails').innerHTML='<p class="batchSummary">Tempo disponibile: <b>'+formattaTempo(batchPlan.minuti)+'</b><br>Kg producibili: <b>'+fmt(batchPlan.kgProducibili)+' kg</b></p>'+(righe.length?righe.join(''):'<p class="batchEmpty">Nessun batch completabile nel periodo selezionato.</p>');$('batchModal').classList.add('on')}
function closeBatchDetails(){$('batchModal').classList.remove('on')}
function useCurrentTimeBatch(){const d=new Date();$('dataPartenzaBatch').value=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');$('oraBatch').value=String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0');calcBatch()}
function resetBatch(){['portataBatch','kb','dataPartenzaBatch','oraBatch','dataFine','oraFine'].forEach(id=>$(id).value='');resetBatchResults();closeBatchDetails()}
function initializeBatch(){['portataBatch','kb','dataPartenzaBatch','oraBatch','dataFine','oraFine'].forEach(id=>$(id).addEventListener('input',calcBatch));$('btnBatch').addEventListener('click',openBatchDetails);calcBatch()}
